### ISSUE TITLE
throws error with opml

### ISSUE THREAD

**Issue by gerroon** [p-e-w/krill#2]
This opml was geenrated by tinytinyrss

Traceback (most recent call last):
  File "/usr/local/bin/krill", line 9, in <module>
    load_entry_point('krill==0.3.0', 'console_scripts', 'krill')()
  File "/usr/local/lib/python2.7/dist-packages/krill-0.3.0-py2.7.egg/krill/krill.py", line 337, in main
    Application(args).run()
  File "/usr/local/lib/python2.7/dist-packages/krill-0.3.0-py2.7.egg/krill/krill.py", line 298, in run
    self.update()
  File "/usr/local/lib/python2.7/dist-packages/krill-0.3.0-py2.7.egg/krill/krill.py", line 272, in update
    for item in self._get_stream_items(source):
  File "/usr/local/lib/python2.7/dist-packages/krill-0.3.0-py2.7.egg/krill/krill.py", line 72, in get_feed_items
    feed_data = feedparser.parse(xml)
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 4014, in parse
    saxparser.parse(source)
  File "/usr/lib/python2.7/dist-packages/drv_libxml2.py", line 214, in parse
    eltName,eltQName,attributesNSImpl) 
  File "/usr/lib/python2.7/dist-packages/feedparser.py", line 1809, in startElementNS
    raise UndeclaredNamespace, "'%s' is not associated with a namespace" % givenprefix
feedparser.UndeclaredNamespace: 'dc' is not associated with a namespace

**Comment by p-e-w** [comment]
It seems that the feed, not the OPML is the actual issue here.

Can you post the OPML file in question? If you do not want to make it public, you can also send it to me by mail (find my email by cloning this repo and running `git log`). Alternatively, you could also debug it yourself by looking for which feed URL it throws the error.
